version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  node-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: node-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network

  react-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
